# Generated by Django 3.1.5 on 2021-01-27 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shortcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=300)),
                ('shortcode', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lastRedirect', models.DateTimeField(auto_now=True)),
                ('redirectCount', models.IntegerField(default=0)),
            ],
        ),
    ]
